CREATE TABLE EMP
(
	EMPCODE NUMERIC(3),
	NAME VARCHAR2(10),
	QUALIFICATION VARCHAR2(7) CONSTRAINT VALID_QUALIF CHECK(QUALIFICATION IN('BTECH','MTECH','MSC','MCA','PHD')),
	PHONE NUMERIC(10),
	EMAIL VARCHAR2(20) CONSTRAINT EMAIL_DOMAIN CHECK(EMAIL LIKE '%@digisol.com'),
	DESIGNATION VARCHAR2(20) CONSTRAINT VALID_DESIGNATION CHECK(DESIGNATION IN('DEVELOPER','PROJECT LEADER','PROJECT MANAGER','TECHNICAL HEAD','PROJECT DIRECTOR','PROJECT LEADER','CEO')),
	SALARY NUMERIC(7) CONSTRAINT SALARY_RANGE CHECK(SALARY BETWEEN 97000 AND 3000000),
	CONSTRAINT PK_EMPNO PRIMARY KEY(EMPCODE)
);

CREATE TABLE SKILL
(
	SKILLID CHAR(3) CONSTRAINT UNQ_SKILLID UNIQUE ,
	SKILLNAME VARCHAR(20) CONSTRAINT UNQ_SKILLNAME UNIQUE
);

CREATE TABLE EMP_SKILL
(
	EMPNO NUMERIC(3),
	CONSTRAINT FK_EMPNO FOREIGN KEY (EMPNO) REFERENCES EMP,
	SKILLID CHAR(3),
	CONSTRAINT FK_SKILLID FOREIGN KEY (SKILLID) REFERENCES SKILL(SKILLID) ON DELETE CASCADE,
	SKILL_EXPERIENCE CHAR(3) CONSTRAINT RAN CHECK(SKILL_EXPERIENCE>0)
);

CREATE TABLE WORK_EXP
(
	EMPCODE NUMERIC(3) REFERENCES EMP,
	PRJID CHAR(3) REFERENCES PRJ_DETAILS,
	WORK_EXPERIENCE NUMERIC(10) NOT NULL CONSTRAINT VALID_EXP CHECK(WORK_EXPERIENCE>0),
	CLIENTID CHAR(3) REFERENCES CLIENT ON DELETE CASCADE,
	RATING CHAR(1) CHECK(RATING IN('A','B','C'))
);

CREATE TABLE CLIENT
(
	CLIENTID CHAR(3),
	CONSTRAINT PK_CLIENTID PRIMARY KEY(CLIENTID),
	CONSTRAINT STRTSWITH_C CHECK(CLIENTID LIKE 'C%'),
	NAME VARCHAR2(10),
	PHONE CHAR(14) CONSTRAINT PHONE_FORMAT CHECK(PHONE LIKE '+91-' OR PHONE LIKE '+81-' OR PHONE LIKE '+31-' OR PHONE LIKE '+48-' OR PHONE LIKE '+44-')
);

CREATE TABLE PRJ_DETAILS
(
	PRJID CHAR(3) CONSTRAINT PK_PRJID PRIMARY KEY CHECK(PRJID LIKE 'P%'),
	PRJ_NAME VARCHAR2(10),
	START_DATE DATE,
	END_DATE DATE,
	ACTUAL_END_DATE DATE,
	LEAD_BY_EMPCODE NUMERIC(3) CONSTRAINT FK_LEAD_EMP REFERENCES EMP,
	BUDGET_ALLOCATED NUMERIC(10,1),
	ACTUAL_BUDGET NUMERIC(10,1),
	CONSTRAINT END_DATE_GREATER_START_DATE CHECK(END_DATE>START_DATE),
	CONSTRAINT ANYL CHECK(ACTUAL_END_DATE >= END_DATE)
);

CREATE TABLE FAMILY_DEPENDENTS
(
	EMPNO NUMERIC(3) REFERENCES EMP,
	DEP_NAME VARCHAR(20),
	RELATIONSHIP VARCHAR(16),
	AGE NUMERIC(3) CONSTRAINT VALID_AGE CHECK(AGE BETWEEN 1 AND 130),
	PRIMARY KEY(EMPNO,DEP_NAME)
);

CREATE TABLE MEDICAL_POLICY
(
	EMPNO REFERENCES EMP,
	POLICYNO VARCHAR(6)CHECK(POLICYNO LIKE 'MED%'),
	PREMIUM NUMERIC(5) CHECK(PREMIUM>0),
	POLICYDATE DATE,
	PRIMARY KEY(POLICYNO,EMPNO)
);

CREATE TABLE PAY_CHECK
(
	EMPCODE REFERENCES EMP,
	PAY_DATE DATE PRIMARY KEY,
	REGULAR_INCREMENT NUMERIC(4) CHECK(REGULAR_INCREMENT LIKE '[2|3|5|7|9][0][0][0]'),
	PERFORMANCE_INCENTIVE NUMERIC(5),
	DA NUMERIC(7),
	PF NUMERIC(6),
	OTHER_INCENTIVES NUMERIC(4),
	ADVANCE_TAX NUMERIC(5)
);

ALTER TABLE EMP ADD REPORTS_TO CONSTRAINT FK_REPORTS_TO_EMPCODE REFERENCES EMP;
ALTER TABLE SKILL ADD CONSTRAINT SKILL_CONST CHECK(SKILLID LIKE 'S%');
ALTER TABLE EMP_SKILL ADD CONSTRAINT PK_EMPNO_SKILLID PRIMARY KEY(EMPNO,SKILLID);
ALTER TABLE PRJ_DETAILS ADD CONSTRAINT UNQ_PRJ_NAME UNIQUE(PRJ_NAME);
ALTER TABLE CLIENT ADD EMAIL VARCHAR2(20) CONSTRAINT VALID_EMAIL CHECK(EMAIL LIKE '%@%.[a-z][a-z][a-z]');
ALTER TABLE EMP ADD CONSTRAINT UNQ_PHONE UNIQUE(PHONE);
ALTER TABLE EMP ADD CONSTRAINT UNQ_EMAIL UNIQUE(EMAIL);
ALTER TABLE MEDICAL_POLICY DROP PRIMARY KEY;
ALTER TABLE MEDICAL_POLICY ADD PRIMARY KEY (EMPNO,POLICYNO,POLICYDATE);
ALTER TABLE MEDICAL_POLICY ADD CONSTRAINT PREM_CHECK CHECK(PREMIUM>1000);
